import type { NextPage, GetStaticProps, InferGetStaticPropsType } from 'next'
import Head from 'next/head'

import { Program } from '../src/components/Program';

import { Product } from '../types/types';

import styles from '../styles/Home.module.scss';

const Home: NextPage = ({products} : InferGetStaticPropsType<typeof getStaticProps>) => {
  console.log(products);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>IPO test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.title}>Специализированные дисциплины</div>
      <div className={styles.study_programs}>
        {products.map((item : Product, i : number) => {
          if (i < 5) {
            return <Program title={item.title} key={item.id} disciplines={item.specializedSubjects}/>
          }
        })}        
      </div>
      <div className={styles.blocks}>
        <div className={styles.red_block}>
          <div className={styles.red_block__rectangle}></div>
          <h3>Практические модули</h3>
          <div className={styles.red_block__content}>
            <span>Работа над собственными проектами: практика групповых взаимодействий, кейс-методы, эссе</span>
          </div>
        </div>
        <div className={styles.black_block}>
          <h3>Итоговая аттестация</h3>
          <ul>
            <li>Бизнес-проектирование (подготовка итоговой аттестационной работы, консультирование по бизнес-проектированию)</li>
            <li>Защита итоговой аттестационной работы</li>
          </ul>
        </div>
      </div>
    </div>
  )
}

export default Home

export const getStaticProps : GetStaticProps = async (context) => {
  const response = await fetch('https://api-moscow-mba.herokuapp.com/products');
  const products : Product[] = await response.json();

  return {
    props: {products},
  }
}
